### ISSUE TITLE
[Integrity] Have no access to Google Play App Signing signature to verify signature in production

### ISSUE THREAD

**Issue by Nek-12** [kevlar-kt/kevlar#1]
This is more of a question because I'm stuck on finding a solution for the problem.

The guide on Integrity outlines that in order to get the app signature, a viable method would be to use the `KevlarIntegrity.obtainCurrentAppSignature` method. Turns out, for developers using the Play App Signing API, the signature that is being used to distribute the APK to devices is managed by google, and is **not** accessible to developers. The only signature we actually have access to is the signature that is used for *uploading* the release  (the upload signature). 

Is there another way to get the actual play store app signature except for adding a log method call to a release build of the app, then uploading this compromised build to play store, obtaining the apk and then examining the output of a rooted device's logcat output?

Even if the signature is going to be obtained, then we still would need to create a separate build config value or a product flavor just to set this signature string, because distributing using an upload signature will now trigger the KevlarIntegrity check fail. Another option is to be stuck with the google play's app signature and upload then download a release from their servers to be able to distribute it to other channels...

The information we __do__ have is the play app signing's certificate fingerprints, and using those seems more appropriate to me, but is it possible inside of the app?

**Comment by cioccarellia** [comment]
I did not see this coming (it's a while I don't publish on the play store).

AFAIK a developer has 2 different signing options:
- Manual signing: Play Signing is disabled, you manage your keystore and have to sign the release APK file yourself, no app bundles. You are responsible for the security of your signing key.
- Play Signing: You manually sign your APK/Bundle with your *Upload Key*, which is optimized and re-signed on Google's end with the *Signing Key* they have on their servers for your app. Those two keys should be different to minimize risks (if you lose your upload key you can request a new one, you don't risk losing [or even having] your signing key, it's much better)

![appsigning_googleplayappsigningdiagram_2x](https://user-images.githubusercontent.com/23010471/190397131-0555fbca-b931-4b65-8156-2bd85a4ac1b8.png)

If your app has been published on the store after August 2021, you must use Play Signing, otherwise you may continue self-signing your software or switch to Play Signing.

Now, as you pointed out, kevlar *could* work both ways: 
- For manual signing, you just need to sign and run the app, and have it spit out the signature;
- For play signing, you *could* create a test build for the play store (which spits out the current signature), sign it with your upload key, upload it, have google sign it with their signing key, grab your signed apk file from the release archive, run it to get your app signature, which you are going to hardcode in next production builds alongside kevlar integrity. This would be a (kinda) once-in-a-key-lifetime procedure to obtain the signing key's signature, but the length of this paragraph begs for a simpler solution.

Focusing on the Play Signing case (as the first one is already working fine), we could add a different signature verification method (alongside the current one) which is based on the certificate's fingerprint (which is less of a hassle to obtain from the play store), and according to your requirements, you can enable either or both.

And I just now realized that if, for any reason, someone [changes their signing key](https://developer.android.com/studio/publish/app-signing#upgrade_key) without being extremely careful, they are going to miserably screw up their key integrity verification process (as this results in some app installs being signed with the old key and some others with the new one). There would need to be a list of allowed signatures (as of today, there's only one) which kevlar regards as trusted.

I'll be working on that.

Material:
- [App Signing](https://developer.android.com/studio/publish/app-signing);
- [Google manual signing documentation](https://developers.google.com/android/guides/client-auth#using_gradles_signing_report);
- [Getting app certificate fingerprint programmatically](https://stackoverflow.com/questions/9293019/get-certificate-fingerprint-from-android-app);
- [Relevant Cryptography Theory](https://security.stackexchange.com/questions/116343/what-is-the-difference-between-a-certificate-a-signature-and-a-thumbprint-in-ca).

**Comment by Nek-12** [comment]
Hello, any progress on this? Should I open a PR completing the task? Sorry for asking for ETAs, just seems like this was forgotten about

**Comment by cioccarellia** [comment]
Sorry, been busy.
With the latest commits I restructured the integrity internal settings mechanisms, so that you can pass to the DSL at the lowest possible level method-specific parameters.

This still needs to be reflected in the documentation. 
Once this issue is done I'll publish a new release.

Feel free to contribute! What you're looking to implement should go in `FingerprintChecker.kt` (in `com.kevlar.integrity.checks`).

**Comment by Nek-12** [comment]
Fixed in #3

**Comment by Nek-12** [comment]
I guess we should close this once the release is out

**Comment by Nek-12** [comment]
@cioccarellia This should be reopened because release 1.1.0 does not contain any code that was merged in #3
