### ISSUE TITLE
[BUG] Rooting: Flags all devices as rooted starting with Android 6.0

### ISSUE THREAD

**Issue by Nek-12** [kevlar-kt/kevlar#10]
## Bug description
In Android Marshmallow, toybox binary was included in the system
https://android.googlesource.com/platform/external/toybox/
https://lwn.net/Articles/629362/

This results in rooting checks fail for ALL devices above Android 6.0 as non-rooted terminal shell now responds positively for the toybox binary.

## Reproduction steps
Run `which toybox` on a device without root on Android 6.0+. 

### Expected behavior
Toybox is not included in the attestation at all.

### Actual behavior
Result will be present, and the attestation will fail.

We shouldn't check for toybox anymore.

**Comment by cioccarellia** [comment]
Hey, sorry for the delay, been really busy

That's not actually a bug: it depends on what you want to be included in your resulting attestation.

If you want to detect toybox (which as you rightfully you pointed out is included from Android M upwards), then you add the `targets { toybox() }` flag, and the attestation will report it. _This doesn't mean that it detected root access though_, it means that it detected toybox.

**Root access** is detected via the `targets { root() }` block. But when you check for something you always have to confirm its presence in the attestation result.

So e.g. if you check for root and toybox and get a non-empty attestation back, you still have to check what it returned, you can't just assume it's root access: it may be either or both.

That's the ideal power of kevlar: you tell it what are the things you are interested in checking, it returns a list of which if those characteristics it found on the running system and you take action accordingly, for each of the returned entries

P.S. the toybox flag is there because you may want to check for it, but you absolutely don't have to if you don't need it.

**Comment by Nek-12** [comment]
Why would I ever want to check for it? Toybox is included as a rooting attestation, there's nothing about the fact it will always report inclusion from android M in the documentation. Your library is a root detection library, I don't think it is a library for always returning `true`

**Comment by cioccarellia** [comment]
I should clarify that in the documentation, as soon as I get some free time I'll make sure to review that.

The attestation mechanism is a fine tool for checking the presence of discrete characteristics/properties on the system. The module is called `rooting` because its main functionality is checking for root access and similar system-wide features (which are all root-related, or at least relevant in that scope).

The following is a **complete** rooting configuration:
```kotlin
private val rooting = KevlarRooting {
    targets {
        root()
        magisk()
        busybox()
        xposed()
        toybox()
    }

    status {
        emulator()
        testKeys()
        selinux {
            flagPermissive()
        }
    }

    allowExplicitRootCheck()
}
```
This means that kevlar, when fired up, will be checking {ROOT, BUSYBOX, MAGISK, XPOSED TOYBOX} + {EMULATOR, TEST_KEYS, SELINUX}, and it will using explicit root access as configured with that flag.

A blank attestation means that **none** of the previous traits have been detected on the system.
A failed attestation (positive) means that **any** of the previous elements may have been detected.
However, you can not infer that root access has been detected (unless your kevlar config only includes root access): to check that you have to collect the attestation and review its contents explicitly, like so:

```kotlin
CoroutineScope(Dispatchers.Default).launch {
    // Attestation request
    when (val attestation = rooting.attestateTargets(context)) {
        is TargetRootingAttestation.Blank -> {
            // Pending attestation, no information yet. 
            // Don't do anything.
        }
        is TargetRootingAttestation.Clear -> {
            // Good to go.
        }
        is TargetRootingAttestation.Failed -> {
            // System modifications detected. See which target(s) and act accordingly: 
            val targets: Set<DetectableSystemTarget> = detectedTargets.detectedTargets
        }
    }
}
```

And then in the `TargetRootingAttestation.Failed` branch you can go ahead and check which `DetectableSystemTarget` is present, and for each act accordingly (by taking direct action / possibly implementing you own custom checks/rules according to your app's logic / security requirements)



On the other hand:
```kotlin
private val rooting = KevlarRooting {
    targets {
        root()
    }
}
```

This way your only test is root access, so if the attestation comes back positive you know root access is detected by kevlar. But that's a special check.


At this point it should be trivial why a toybox check is in the library: there have been a few apps and tools that check for toybox in the host system and make assumption / decisions with regards to it, so I decided to include it since it's a pretty innocuous flag to have, it doesn't cost anything if you don't run it but it's in the battery of tests that you can launch.
